apiVersion: v1
kind: Service
metadata:
  name: dev-api-service
  labels:
    app: dev-api-service
    env: dev
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: dev-api-service
    env: dev