apiVersion: v1
kind: Service
metadata:
  name: stage-api-service
  labels:
    app: stage-api-service
    env: stage
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: stage-api-service
    env: stage