apiVersion: v1
kind: Service
metadata:
  name: prod-api-service
  labels:
    app: prod-api-service
    env: prod
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: prod-api-service
    env: prod